name: 'Deploy back end'

on:
  push:
    branches: [ master, main ]
    paths: [ "back-end/**" ]
  pull_request:
    branches: [ master ]
    paths: [ "back-end/**.tf", "back-end/**.py" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Configure credentials
        run: echo "[default]\naws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        
      - name: Terraform Init
        working-directory: ./back-end
        run: terraform init
      
      - name: Terraform Format
        working-directory: ./back-end
        run: terraform fmt -check
      
      - name: Terraform Plan
        working-directory: ./back-end
        run: terraform plan

  apply:
    name: Apply
    if: startsWith(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    environment: production
    needs: [ lint ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Configure credentials
        run: echo "[default]\naws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        
      - name: Terraform Init
        working-directory: ./back-end
        run: terraform init
      
      - name: Terraform Plan
        working-directory: ./back-end
        run: terraform plan -out=plan.plan
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        working-directory: ./back-end
        run: terraform apply -auto-approve
