name: 'Deploy back end'

on:
  push:
    branches: [ master, main ]
    paths: [ "back-end/**" ]
  pull_request:
    branches: [ master ]
    paths: [ "back-end/**.tf", "back-end/**.py" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
  TF_VAR_backend_bucket: ${{ secrets.BACKEND_BUCKET }}
  TF_VAR_resume_bucket: ${{ secrets.RESUME_BUCKET }}
  TF_VAR_cloudfront_distribution_id: ${{ secrets.CF_DIST_ID }}
  TF_VAR_dynamodb_table_name: ${{ secrets.DYNAMODB_TABLE_NAME }}
  TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
  TF_VAR_cicd_resume_policy: ${{ secrets.CICD_RESUME_POLICY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Check environment vars
        run: env
      
      - name: Terraform Init
        working-directory: ./back-end
        run: terraform init
      
      - name: Terraform Format
        working-directory: ./back-end
        run: terraform fmt -check
      
      - name: Terraform Plan
        working-directory: ./back-end
        run: terraform plan

  apply:
    name: Apply
    if: startsWith(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    environment: production
    needs: [ lint ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        working-directory: ./back-end
        run: env && terraform init
      
      - name: Terraform Plan
        working-directory: ./back-end
        run: terraform plan -out=plan.plan
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        working-directory: ./back-end
        run: terraform apply -auto-approve
