# This is a basic workflow to help you get started with Actions

name: 'Deploy front end'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    paths: [ "./front-end/*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: sudo apt-get install tidy eslint awscli -yqq
      
      - name: Validate and lint files
        run: |
          tidy -eq ./front-end/*.html
      #    # csslint ./front-end/*.css
      #    eslint ./front-end/*.js

      # Runs a single command using the runners shell
      - name: Upload the files to S3
        run: |
          for FILE in front-end/*; do
            aws s3 cp "./front-end/$FILE" "s3://${S3_BUCKET_NAME}/${FILE}"
          done
      
      - name: Invalidate the Cloudfront Cache
        run: aws cloudfront create-invalidation --distribution-id "${CF_DIST_ID}" --paths /*
